#!/usr/bin/env python
import os
import datetime

class ReportGenerator:
    def __init__(self, filename="vulnerability_report.html"):
        self.filename = filename
        self.results = []
        self.title = "SigPloit Vulnerability Scan Report"
        
    def add_result(self, module, target, status, details):
        self.results.append({
            "module": module,
            "target": target,
            "status": status,
            "details": details,
            "time": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        })
        
    def generate(self):
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>{self.title}</title>
            <style>
                body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background-color: #f0f2f5; }}
                .container {{ max-width: 1000px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 8px; box-shadow: 0 0 15px rgba(0,0,0,0.1); }}
                h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
                .summary {{ background-color: #ecf0f1; padding: 15px; border-radius: 5px; margin-bottom: 20px; }}
                table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
                th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
                th {{ background-color: #34495e; color: white; }}
                tr:hover {{ background-color: #f5f5f5; }}
                .status-high {{ color: #c0392b; font-weight: bold; }}
                .status-medium {{ color: #e67e22; font-weight: bold; }}
                .status-info {{ color: #2980b9; font-weight: bold; }}
                .footer {{ margin-top: 30px; text-align: center; color: #7f8c8d; font-size: 0.9em; }}
            </style>
        </head>
        <body>
            <div class="container">
                <h1>{self.title}</h1>
                <div class="summary">
                    <p><strong>Date:</strong> {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
                    <p><strong>Total Scans:</strong> {len(self.results)}</p>
                </div>
                
                <table>
                    <thead>
                        <tr>
                            <th>Time</th>
                            <th>Module</th>
                            <th>Target</th>
                            <th>Status</th>
                            <th>Details</th>
                        </tr>
                    </thead>
                    <tbody>
        """
        
        for res in self.results:
            status_class = "status-info"
            if "VULNERABLE" in res['status'] or "GATEWAY FOUND" in res['status']:
                status_class = "status-high"
            elif "TIMEOUT" in res['status']:
                status_class = "status-medium"
                
            html += f"""
                        <tr>
                            <td>{res['time']}</td>
                            <td>{res['module']}</td>
                            <td>{res['target']}</td>
                            <td class="{status_class}">{res['status']}</td>
                            <td>{res['details']}</td>
                        </tr>
            """
            
        html += """
                    </tbody>
                </table>
                <div class="footer">
                    Generated by SigPloit Framework
                </div>
            </div>
        </body>
        </html>
        """
        
        with open(self.filename, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"\n[+] Report generated successfully: {os.path.abspath(self.filename)}")

    def export_json(self, filename=None):
        """Export results to JSON format."""
        import json
        
        if filename is None:
            filename = self.filename.replace('.html', '.json')
        
        report = {
            'title': self.title,
            'generated': datetime.datetime.now().isoformat(),
            'total_scans': len(self.results),
            'results': self.results,
            'summary': {
                'vulnerable': sum(1 for r in self.results if 'VULNERABLE' in r['status'] or 'GATEWAY FOUND' in r['status']),
                'timeout': sum(1 for r in self.results if 'TIMEOUT' in r['status']),
                'info': sum(1 for r in self.results if 'VULNERABLE' not in r['status'] and 'GATEWAY FOUND' not in r['status'] and 'TIMEOUT' not in r['status']),
            }
        }
        
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2, ensure_ascii=False)
        print(f"\n[+] JSON report exported: {os.path.abspath(filename)}")
    
    def export_csv(self, filename=None):
        """Export results to CSV format."""
        import csv
        
        if filename is None:
            filename = self.filename.replace('.html', '.csv')
        
        with open(filename, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(['Time', 'Module', 'Target', 'Status', 'Details'])
            for res in self.results:
                writer.writerow([res['time'], res['module'], res['target'], res['status'], res['details']])
        
        print(f"\n[+] CSV report exported: {os.path.abspath(filename)}")


if __name__ == "__main__":
    # Test
    report = ReportGenerator("test_report.html")
    report.add_result("SS7 Scanner", "10.0.0.1", "GATEWAY FOUND", "SCTP Port 2905 Open")
    report.add_result("SRI Attack", "905551234567", "VULNERABLE", "IMSI Leaked: 286011234567890")
    report.generate()
    report.export_json()
    report.export_csv()
